domain:
  x0:
    type: float
    low: 0.
    high: 1.
  x1:
    type: float
    low: 0.
    high: 1.

experimentdata:
  from_sampling:
    domain: ${domain}
    sampler: random
    seed: 1
    n_samples: 10
