defaults:
  - 7d_domain
  - override hydra/job_logging: custom

experimentdata:
  from_file: ./example_design

  # from_sampling:
  #   sampler: latin
  #   seed: 42
  #   n_samples: 3
  #   domain: ${domain}

mode: sequential

hpc:
  jobid: -1

imperfection:
  mean: -2.705021452041446
  sigma: 0.293560379208524
  domain:
    imperfection:
      type: float
      low: 0.0
      high: 1.0

scripts:
  lin_buckle_pre: ./scripts/supercompressible_lin_buckle.py
  lin_buckle_post:  ./scripts/supercompressible_lin_buckle_pp.py
  riks_pre: ./scripts/supercompressible_riks.py
  riks_post: ./scripts/supercompressible_riks_pp.py


log_level: 20