# hydra.yaml
design:
  input_space:
    - name: x0
      class: ContinuousParameter
      lower_bound: -1.0
      upper_bound: 1.0
    - name: x1
      class: ContinuousParameter
      lower_bound: -1.0
      upper_bound: 1.0
    - name: x2
      class: DiscreteParameter
      lower_bound: 3
      upper_bound: 7
    - name: x4
      class: CategoricalParameter
      categories: ["test1", "test2", "test3"]

  output_space:
    - name: y
      class: ContinuousParameter
