defaults:
  - default

design:
  lower_bound: -3.0
  upper_bound: 3.5
  dimensionality: 2

function:
  function_name: Levy
  noise: 1.1

optimizer:
  optimizer_name: Momentum

sampler:
  sampler_name: LatinHypercubeSampling

execution:
  iterations: 140
  realizations: 6
  parallelization: False